hayes/pothos

packages/converter/CHANGELOG.md, packages/converter/package.json, packages/core/CHANGELOG.md, packages/core/package.json, packages/core/src/config-store.ts, packages/core/src/fieldUtils/base.ts, packages/core/src/fieldUtils/input.ts, packages/core/src/refs/field.ts, packages/core/src/refs/input-field.ts
fixes #22 
Previously when using TS enums for types or arguments, if the GraphQL type was not implemented, the error message would not be very helpful.
TS enums do not have names at runtime, and without an implementation naming them is not possible.  Instead, this change will track some additional information about the names of field references so that the generated errors can point at a more specific issues.
Example error after this change when enum is used as an arugment:
```
Error: Missing implementations for some references (<unnamed ref or enum: used by Giraffe.foo(arg1)>).
at ConfigStore.prepareForBuild (/Users/michael.hayes/code/giraphql/packages/core/src/config-store.ts:354:13)
at SchemaBuilder.toSchema (/Users/michael.hayes/code/giraphql/packages/core/src/builder.ts:537:22)
``` …
=> feat: improve error messages for unresolved refs and allow arguments to be implemented after references

docs/guide/enums.md
1. Lists where showing 1./1./1. because of the breaks caused by the code examples.
1. Arbitrary line breaks in paragraphs
=> More doc fixes

packages/plugin-relay/src/field-builder.ts
I'm like 90% sure this was the correct place to make this change but if not please let me know 😄 
Fixes #64
=> Make relay connection args optional explicitly

docs/plugins/dataloader.md
The validation plugin is not necessary for the dataloader package. This was probably a copy + paste mistake from the validation plugin docs.
=> docs(plugins/dataloader): copy paste mistake

.changeset/few-houses-raise.md, packages/plugin-prisma/src/types.ts
I found out that this was causing issues with PascalCase model names in Prisma. We really just need to convert the first letter to lowercase, not the entire model name.
=> Use Uncapitalize instead of Lowercase for prisma. 

.changeset/lazy-dryers-listen.md, packages/plugin-dataloader/src/global-types.ts, packages/plugin-dataloader/src/schema-builder.ts, packages/plugin-dataloader/src/types.ts, packages/plugin-dataloader/tests/__snapshots__/index.test.ts.snap, packages/plugin-dataloader/tests/example/schema/index.ts, packages/plugin-dataloader/tests/index.test.ts
🦋  @giraphql/converter@0.0.0-preview-202178194614
🦋  @giraphql/core@0.0.0-preview-202178194614
🦋  @giraphql/deno@0.0.0-preview-202178194614
🦋  @giraphql/plugin-dataloader@0.0.0-preview-202178194614
🦋  @giraphql/plugin-directives@0.0.0-preview-202178194614
🦋  @giraphql/plugin-errors@0.0.0-preview-202178194614
🦋  @giraphql/plugin-example@0.0.0-preview-202178194614
🦋  @giraphql/plugin-mocks@0.0.0-preview-202178194614
🦋  @giraphql/plugin-prisma@0.0.0-preview-202178194614
🦋  @giraphql/plugin-relay@0.0.0-preview-202178194614
🦋  @giraphql/plugin-scope-auth@0.0.0-preview-202178194614
🦋  @giraphql/plugin-simple-objects@0.0.0-preview-202178194614
🦋  @giraphql/plugin-smart-subscriptions@0.0.0-preview-202178194614
🦋  @giraphql/plugin-sub-graph@0.0.0-preview-202178194614
🦋 …
=> feature: support refs and classes in dataloader objects

docs/plugins/relay.md
Removed paragraph about empty objects as the example above no longer follows this convention
=> Empty option objects

packages/plugin-validation/tests/example/schema/index.ts, packages/plugin-validation/tests/index.test.ts
hey @hayes! 
We ran into a validation plugin bug where:
1. if `validate` is on the input object, it does not run unless a `validate` is added to a field on the input object
2. validate can take an array of arrays, but only one is run and the last one (which if succeeds, the whole validation seems to succeed?)
Ad you can see, when we add `validate` to a field, it makes the validate on the input field work again, hence why there is an error in the response. Whereas, if the `validate` on the field is missing, no `validate` is run on the input object.
=> tests for validation on input

.changeset/brave-forks-kick.md, packages/deno/packages/plugin-scope-auth/index.ts, packages/plugin-scope-auth/src/index.ts
In order to be able to skip reporting to Sentry any authentication errors (using https://www.envelop.dev/plugins/use-sentry), it's required to have access to the class of ForbiddenError, which currently is not possible because it was not exported from the index nor it's possible to do deep imports because the `exports` of the package don't allow it:
```json
{
"name": "@pothos/plugin-scope-auth",
"version": "3.0.0",
"description": "A Pothos plugin for adding scope based authorization checks to your GraphQL Schema",
"main": "./lib/index.js",
"types": "./lib/index.d.ts",
"module": "./esm/index.js",
"exports": {
"import": "./esm/index.js",
"require": "./lib/index.js"
},
```
---
Now in a separate but related note, I would also like to have the freedom to customize the whole error instance used …
=> fix: export ForbiddenError for re-use

.changeset/pretty-laws-kiss.md, packages/plugin-scope-auth/src/resolve-helper.ts, packages/plugin-scope-auth/src/types.ts, packages/plugin-scope-auth/tests/example/schema/custom-errors.ts, website/pages/docs/plugins/scope-auth.mdx
@PabloSzx I realized that I made a mistake when I added the `unauthorizedError` logic.  I think you are the only one using it so far, so I am going to release this as a minor version.
Basically, I need to remove the args option from the global callback.  I have some work in progress to allow authorization checks that will not work if the global error formater takes args.
=> Remove args from global unauthorizedError callback

.changeset/neat-cobras-ring.md, packages/plugin-relay/src/schema-builder.ts
`PageInfo` is nullable when `defaultFieldNullability` is `true`, but [the relay spec indicates, that `PageInfo` must not be nullable](https://relay.dev/graphql/connections.htm#sec-Connection-Types.Fields.PageInfo)
=> fix: explicitly make pageInfo non nullable

website/pages/docs/guide/schema-builder.mdx
I see you're limiting line length, probably in your md editor, which isn't a problem for composing regular paragraphs (md compilers usually ignore single linebreaks), but it gets messed up when you have a number list because it creates second paragraphs under the first line of the number (ie "1.", "2.", etc) instead of adding to the first line.
=> fix linebreaks in final html

website/pages/docs/plugins/federation.mdx
I've been stumbling around with apollo yelling at me trying to get federation to work, and it eventually lead me to issue #427. Switching to `printSubgraphSchema` fixed the problem, but I did not try your other suggested alternative.
=> Update federation.mdx wrt. printing schema

website/pages/docs/plugins/sub-graph.mdx
If I'm understanding the remaining docs for this plugin and the types correctly then the initial example on the subgraphs page is incorrect. This PR fixes that.
=> Fix sub-graph.mdx

.changeset/kind-mangos-rule.md, packages/plugin-complexity/src/index.ts
Right now the complexityError can only be set using the builder options.
=> fix: respect options.complexity.complexityError

.changeset/nine-readers-rush.md, packages/plugin-prisma/src/generator.ts
Fixes #553
This is a temporary workaround while full-text search is in preview (since August 2021), and should be removed as soon as it reaches stable (no ETA yet).
`WithAggregation` seems to be disabled by https://github.com/prisma/prisma-engines/blob/1b996e940dc3998d2003ab429f3ac9a3f98a1fbd/query-engine/schema-builder/src/input_types/fields/arguments.rs#L99-L102
=> fix(#553): use the right types when fullTextSearch is enabled

.changeset/fluffy-grapes-enjoy.md, packages/plugin-prisma/src/generator.ts
Related issue: #575 
Thanks to https://github.com/hayes/pothos/commit/521cde32f3a223cf5479322418a911f4a467f60e , the default location of the file of generated prisma fields is now correctly set, but missing `.ts` extension confuses module resolution.
I think adding `.ts` is also needed to keep consistency as `generated.ts` is expected filename and it is used in several place, e.g. https://github.com/hayes/pothos/blob/7cbbbe7315b2e5cd2275c1ba0c043d6a2d76abb5/packages/plugin-prisma/prisma/schema.prisma#L17
=> Fix: add .ts extension to filename for generated prisma fields

.changeset/curvy-olives-argue.md, packages/plugin-authz/README.md, packages/plugin-authz/src/types.ts, packages/plugin-authz/tests/example/data.ts, packages/plugin-authz/tests/example/schema/index.ts, packages/plugin-authz/tests/index.test.ts, website/pages/docs/plugins/authz.mdx
The AuthZ security layer supports a few more ways to configure authorization rules than what's currently available in the AuthZ plugin. 
For example, if you want to allow an admin user access to many endpoints in your API, you would (with the current implementation of the plugin) need to update all AuthZ rules and add an explicit admin role check. But AuthZ also allows you to write [inline composite rules](https://github.com/AstrumU/graphql-authz#inline-composition-rules), with which you could write an 'IsAdmin' rule just once, and use simple boolean logic to add admin access to endpoints without touching the other rule implementations. 
This PR updates the implementation, the tests and the plugin documentation.
=> Add support for inline composite rules to AuthZ plugin

examples/prisma-federation/README.md, examples/prisma-federation/package.json, examples/prisma-federation/src/comments/index.ts, examples/prisma-federation/src/gateway.ts, examples/prisma-federation/src/posts/index.ts, examples/prisma-federation/src/server.ts, examples/prisma-federation/src/servers.ts, examples/prisma-federation/src/users/index.ts, packages/deno/packages/plugin-directives/mock-ast.ts, packages/plugin-federation/README.md, packages/plugin-federation/package.json, packages/plugin-federation/tests/example/accounts/index.ts, packages/plugin-federation/tests/example/compatibility/products/index.ts, packages/plugin-federation/tests/example/compatibility/server.ts, packages/plugin-federation/tests/example/gateway.ts, packages/plugin-federation/tests/example/inventory/index.ts, packages/plugin-federation/tests/example/products/index.ts, packages/plugin-federation/tests/example/reviews/index.ts, packages/plugin-federation/tests/example/server.ts, packages/plugin-federation/tests/example/servers.ts, packages/plugin-federation/tests/index.test.ts, pnpm-lock.yaml, website/pages/docs/guide/app-layout.mdx, website/pages/docs/plugins/federation.mdx
Apollo released version 4 of their server but onder a new package. 
This pull request will upgrade to the `@apollo/server` package
=> rename and update imports from apollo-server and apollo-server-core to @apollo/server

.changeset/fresh-eels-shop.md, packages/plugin-relay/src/schema-builder.ts, packages/plugin-relay/tests/__snapshots__/index.test.ts.snap, packages/plugin-relay/tests/examples/node-with-interfaces/builder.ts, packages/plugin-relay/tests/examples/node-with-interfaces/data.ts, packages/plugin-relay/tests/examples/node-with-interfaces/schema/index.ts, packages/plugin-relay/tests/examples/node-with-interfaces/server.ts, packages/plugin-relay/tests/examples/node-with-interfaces/types.ts, packages/plugin-relay/tests/index.test.ts
When passing the `interfaces` field to `builder.node` as a function that returns an array (rather than the array directly), a runtime error was occurring. 
The reason was that line `223` of the file changed in this PR was using the spread operator on the passed `interfaces`, which crashes if the value is a function. The compiler didn't catch this because the `as` operator was coercing the value as an array.
=> Fix lazy interfaces on nodes

.changeset/twelve-tables-itch.md, packages/deno/packages/plugin-relay/global-types.ts, packages/plugin-relay/src/global-types.ts
**Original Problem:** I noticed this because I was trying to create a connection with additional fields. Something along the lines of:
```typescript
users: t.connection(
{
type: GraphQLUser,
resolve: (users, args) => {
const connection = resolveArrayConnection({ args }, users)
return <typeof connection & { totalCount: number }>{
totalCount: recipients.length,
...connection,
}
},
},
{
fields: tc => ({
totalCount: tc.int({ resolve: x => x.totalCount }),
}),
}
),
```
This worked fine on object types, but when I tried this on an interface, the resolver for the `totalCount` int field wasn't aware that the return value of the connection's resolve included a `totalCount` field, so I wasn't able to resolve the value for the `int`. 
**Cause:** I realized that the conditional type changed in this …
=> Fix types on connection fields on interfaces

.changeset/tidy-needles-hang.md, package.json, packages/core/src/builder.ts, packages/core/tests/__snapshots__/patterns.test.ts.snap, packages/core/tests/examples/patterns/builder.ts, packages/core/tests/examples/patterns/types/circular.ts, pnpm-lock.yaml
Fixes the following issue:
When attempting to refer to `Query` as a ref. This isn't super common, but can be a useful pattern for cases where you want to return `Query` as a type off of a `Mutation` result.
Also fixes the `pnpm coverage` command
There's probably an opportunity to run `builder.queryType` through `builder.objectType` (what [nexus does](https://github.com/graphql-nexus/nexus/blob/1e6b9212d351e4c05504590ad70b65b2ee0c1f7a/src/definitions/queryType.ts#L42-L44)), allowing interfaces and such, since a `Query` object is just a regular object which also happens to be designated as the root type if another isn't specified.
Looking forward to digging in more here to figure out how this can play nicely with Nexus 😄
=> Add Query type ref to type config

website/pages/docs/migrations/index.mdx
Mention the codemod I built that enables to migrate from Nexus to Pothos. Further usage instructions resides in the readme of the repo.
=> Mention nexus to pothos codemod in the migration docs

.changeset/slow-tigers-fail.md, CONTRIBUTING.md, packages/plugin-errors/README.md, packages/plugin-errors/src/index.ts, packages/plugin-errors/src/types.ts, packages/plugin-errors/tests/__snapshots__/index.test.ts.snap, packages/plugin-errors/tests/example/builder.ts, packages/plugin-errors/tests/example/schema.ts, packages/plugin-errors/tests/index.test.ts, website/pages/docs/plugins/errors.mdx
Adds an option for the `@pothos/plugin-errors` plugin to customize how type names are generated. 
This new option could be used like:
```typescript
export const builderWithCustomErrorTypeNames = new SchemaBuilder<{}>({
plugins: [ErrorPlugin, ValidationPlugin],
errorOptions: {
defaultTypes: [Error],
defaultGetTypeName: ({ fieldName, kind }) => `${fieldName}${kind}`,
},
});
```
The above would get rid of the `Query|Mutation` prefix that is added automatically to these types, in case users want to modify these.
Resolves https://github.com/hayes/pothos/issues/566
Docs screenshot:
=> add function to compute custom name for errors plugin generated types

website/pages/docs/guide/objects.mdx, website/pages/index.mdx
Make minor typo fixes to index.mdx and objects.mdx
Fix minor typos, ignoring anything that could change meaning.
=> Make minor typo fixes to website copy

packages/core/src/config-store.ts
Changed "for for" to "for" in a custom error message.
The typo also appears in `packages/deno/packages/core/config-store.ts`, however it appears this is a generated artifact based on the core package config store file. With that being said, I'm not exactly sure if it needs to be manually fixed in that file as well (I assume not, but let me know).
=> fix: remove duplicate word typo

examples/nextjs/package.json, examples/nextjs/pages/api/graphql.ts, pnpm-lock.yaml
Fixes #761.
Sorry for the pnpm-lock.yaml noise, I used the same pnpm version as in `package.yaml` but it didn't help. Perhaps you can reset it and push the regenerated lockfile to my branch (assuming that it even matters).
=> Rewrite the nextjs example to use Yoga

packages/plugin-mocks/README.md, packages/plugin-sub-graph/README.md, website/pages/docs/plugins/mocks.mdx, website/pages/docs/plugins/sub-graph.mdx
Make website and README changes for plugins:
1. Fix typos in the **SubGraph plugin**, making sure to make the same changes in the corresponding README.
2. Fix typos in the **Mocks plugin**, making sure to make the same changes in the corresponding README.
3. Remove Mocks plugin info from **SubGraph plugin** documentation.
Ignore anything that could change meaning.
=> Fix typos on website's plugin pages, and in corresponding READMEs

website/pages/docs/plugins/complexity.mdx
Fixed syntax from this:- 
```
defaultComplexity: 1,
defaultListMultiplier: 10,
complexity: {
limit: (ctx) => ({
complexity: 500,
depth: 10,
breadth: 50,
}),
}
```
To this:-
```
complexity: {
defaultComplexity: 1,
defaultListMultiplier: 10,
limit: (ctx) => ({
complexity: 500,
depth: 10,
breadth: 50,
}),
}
```
=> fixed complexity plugin code example

.changeset/fifty-cooks-cheer.md, packages/converter/tests/__snapshots__/index.test.ts.snap, packages/converter/tests/examples/random-stuff.ts, packages/core/src/types/builder-options.ts, packages/deno/packages/core/types/builder-options.ts
Changes `ParentShape[K]` to `Awaited<ParentShape[K]>` for determining if a field can be exposed via `.expose*` and for nullability
Closes #793
=> feat: unwrap Promise fields for expose, fixes #793

.changeset/early-chefs-end.md, packages/deno/packages/plugin-relay/utils/global-ids.ts, packages/plugin-relay/src/utils/global-ids.ts, packages/plugin-relay/tests/__snapshots__/index.test.ts.snap, packages/plugin-relay/tests/examples/relay/schema/numbers.ts, packages/plugin-relay/tests/index.test.ts
It's an edge case, but if an ID were to have a `:` in it for some reason, this change ensures that it gets included rather than splitting and only including the first value after the typename `:` delimiter
=> feat: handle string contining ':' in global ID

packages/deno/packages/plugin-relay/field-builder.ts, packages/deno/packages/plugin-relay/index.ts, packages/deno/packages/plugin-relay/input-field-builder.ts, packages/deno/packages/plugin-tracing/README.md, packages/plugin-relay/src/field-builder.ts, packages/plugin-relay/src/index.ts, packages/plugin-relay/src/input-field-builder.ts, packages/plugin-relay/tests/examples/global-connection-fields/schema/numbers.ts, packages/plugin-relay/tests/examples/relay/schema/numbers.ts
Was working on adding `parse` to `loadableNode` - got pretty close to having it correct, but while working through the implementation I ran into a few bugs that seemed better to address separately before changing things around a bit for that.
The inferred types for `parse` are not properly reflecting the runtime coercion.
One of the issues was because `parse` was supposed to be `parseId` in the `relayGlobalIDFor`. The other issue is that it wasn't decoding the ids when passed to a field like `node`.
Not sure if this is 100% correct, the `parse` -> `parseId` seemed to just be an oversight, but wasn't sure if there was something else I was missing in the other changes.
=> bug: failing tests & fixes for id coercion

.changeset/nasty-trainers-remember.md, packages/deno/packages/core/config-store.ts, packages/deno/packages/plugin-directives/mock-ast.ts, packages/deno/packages/plugin-relay/README.md, packages/plugin-directives/src/mock-ast.ts, packages/plugin-directives/tests/__snapshots__/index.test.ts.snap, packages/plugin-directives/tests/example/schema/index.ts, packages/plugin-directives/tests/index.test.ts
We are migrating from Federation v1 spec to Federation v2, and for that, we need to change from using `printSchema` from `graphql` to `printSubgraphSchema` from `@apollo/subgraph`. Unfortunately, `printSubgraphSchema` is relying on the `astNode` to get the `defaultValue`s for inputs and arguments, so when printing the schema to the disk, we are missing those defaults from the schema. This is causing breaking changes when pushing the new schema (now with Fed v2+) to the registry.
* This PR makes sure we add the `defaultValue` to the `astNode` for both the arguments and the input fields.
https://github.com/apollographql/federation/issues/2438
=> [Fix]: Add defaultValue for args and input fields

packages/plugin-sub-graph/src/index.ts
Partial Fix for #856 
Sorry but I could not fix `deprecated` for query input args. Just did not find it.
=> In SubGraph Plugin: deprecation hints in InputTypes and Args

.changeset/pink-falcons-rule.md, packages/deno/packages/plugin-relay/schema-builder.ts, packages/plugin-relay/src/schema-builder.ts
This will also apply `idFieldOptions` to the Node interface. My goal was to give the Node interface's ID field a description:
```ts
const schemaBuilder = new SchemaBuilder({
plugins: [RelayPlugin],
relayOptions: {
idFieldOptions: {
description: "The node’s globally unique identifier.",
},
},
};
```
```graphql
interface Node {
"The node’s globally unique identifier."
id: ID!
}
```
=> Include `idFieldOptions` in the Node interface ID field

.github/workflows/changesets.yml, packages/converter/package.json, packages/core/package.json, packages/deno/package.json, packages/plugin-add-graphql/package.json, packages/plugin-authz/package.json, packages/plugin-complexity/package.json, packages/plugin-dataloader/package.json, packages/plugin-directives/package.json, packages/plugin-errors/package.json, packages/plugin-example/package.json, packages/plugin-federation/package.json, packages/plugin-mocks/package.json, packages/plugin-prisma-utils/package.json, packages/plugin-prisma/package.json, packages/plugin-relay/package.json, packages/plugin-scope-auth/package.json, packages/plugin-simple-objects/package.json, packages/plugin-smart-subscriptions/package.json, packages/plugin-sub-graph/package.json, packages/plugin-tracing/package.json, packages/plugin-validation/package.json, packages/plugin-with-input/package.json, packages/test-utils/package.json, packages/tracing-newrelic/package.json, packages/tracing-opentelemetry/package.json, packages/tracing-sentry/package.json, packages/tracing-xray/package.json
A while ago npm released [provenance](https://docs.npmjs.com/generating-provenance-statements) which allows us to automate a proof that a version was published from an authorized CI, this to provide an initial tool against supply-chain attacks.
The premise to make this work is
- publish from Github Actions
- have the `repository` field set correctly in packages
- add `permissions` to the action
An example of how this looks on npm can be seen [here](https://www.npmjs.com/package/hoofd) at the bottom of the page.
=> chore(workspace): publish packages with provenance

.changeset/twenty-years-search.md, packages/core/src/builder.ts, packages/core/src/types/builder-options.ts, packages/core/src/utils/enums.ts, packages/core/tests/__snapshots__/index.test.ts.snap, packages/core/tests/examples/random-stuff.ts
Hey!
I'm working on a pull request to add the ability to also optionally specify graphql metadata (description, deprecationReason, and extensions) for an enum type, even if the enum type is provided as a TypeScript enum. Because currently, you cannot do this:
```ts
enum SomeTypescriptEnum {
bla = "bla",
yeah = "yeah",
}
builder.enumType(SomeTypescriptEnum, {
name: "SomeTypescriptEnum",
// not currently possible:
values: {
bla: {
deprecationReason: "We don't use this anymore for some reason",
},
}.
});
```
The actual JS fix is simple, but the TypeScript typings are a bit more complicated, and then it'll also require some changes in the other packages and docs I think, before this PR can be complete.
The first commit I just added allows the core package to build successfully, although I'm …
=> Add ability to configure meta for builder.enumType(<ts enum>)

website/components/Docs/Toc.tsx, website/components/Layout.tsx
Thank you for the useful library.
I noticed a small discomfort while reading the documentation.
`GitHub` recommends capitalizing the "H"
This has nothing to do with the core of the library, but it would be a shame to suffer from a slight discomfort in the documentation. Please consider incorporating this change if possible.😃
=> Change `Github` to `GitHub` in the docs

.changeset/few-turtles-tell.md, packages/plugin-prisma/src/generator.ts
When you have a Prisma model where one of the required fields are of an unsupported type, Prisma does not generate a `prisma.modelName.create` function, so rows of this type can only be created through raw queries. A problem behind this is that the `generated.ts` file gets an error trying to reference a non-existent type from Prisma, and we're not able to compile with `tsc` (even with skipLibCheck).
This PR makes necessary adjustments on Pothos' prisma plugin generator in order to not try to use the `Prisma.${modelName}CreateInput` when it is not available.
=> stop using unavailable prisma CreateInput objects

.changeset/wild-swans-heal.md, packages/plugin-complexity/src/index.ts, packages/plugin-complexity/src/validator.ts, packages/plugin-complexity/tests/__snapshots__/index.test.ts.snap, packages/plugin-complexity/tests/index.test.ts
hi all!
thanks for that awesome library. it's way easier to implement a graphql api using it!
while experimenting with it, i noticed that the plugin `@pothos/plugin-complexity` interprets zero-values as just an undefined limit.
i expect that a zero-value means that a limit is reached, just like a negative value.
i've changed the truthy comparison to a `typeof <limit name> === 'number'` where applicable. i've also added some test cases that cover zero-values and negatives (already supported, but just in case...).
i'd be glad if you consider incorporating this change.
=> plugin-complexity: fix bug when limits are zero

.changeset/smooth-oranges-drive.md, packages/plugin-prisma-utils/src/global-types.ts, packages/plugin-prisma-utils/src/schema-builder.ts, packages/plugin-prisma-utils/src/types.ts, packages/plugin-prisma-utils/tests/__snapshots__/codegen.test.ts.snap, packages/plugin-prisma-utils/tests/codegen.test.ts, packages/plugin-prisma-utils/tests/examples/codegen/generator.ts, packages/plugin-prisma-utils/tests/examples/codegen/schema.graphql, packages/plugin-prisma-utils/tests/examples/codegen/schema/prisma-inputs.ts
With this change, the `mode` field can be added to scalar filter types, which allows to do queries like this:
```graphql
{
users(filter: {email: {contains: "GMAIL", mode: Insensitive}}) {
id
email
}
}
```
I tested the query with the "codegen" example:
```sh
node -r @swc-node/register packages/plugin-prisma-utils/tests/examples/codegen/server.ts
```
Fixes #937
=> Allow `mode` in generated Prisma scalar filter types

.changeset/twenty-cups-marry.md, packages/plugin-prisma/src/util/map-query.ts, packages/plugin-prisma/tests/index.test.ts
Related to https://github.com/hayes/pothos/issues/723
=> Support Client Directives in Prisma plugin (@skip and @include)

.changeset/nice-crabs-melt.md, packages/plugin-prisma/src/index.ts
**Description**
- Expose `prismaModelKey` symbol from `@pothos/plugin-prisma`
**Context**
Hi, I'm author of pothos-plugin-effect which a Pothos plugin for integration with Effect ecosystem. Recently, I've been working on integrate with prisma plugin and realized that I needed to access `prismaModelKey` to resovle typing.
Here is my pull reqeust: https://github.com/iamchanii/pothos-plugin-effect/pull/19. (I will be glad if you can review about it especially [here](https://github.com/iamchanii/pothos-plugin-effect/blob/29d4709889d614ca68c07e3c8736371eb583fa5c/src/global-types.ts#L159-L167) :wink:)
I temporarily worked through the `pnpm patch`. I hope to see this PR merged then I'll release `t.prismaEffect` feature with new prisma-plugin depends.
=> Expose prismaModelKey

website/pages/docs/plugins/validation.mdx
Add documentation for providing a Zod schema object to validate a whole field. When I was trying to implement this, it was not previously clear that I could, so hopefully this will make it a little bit clearer.
=> Update validation plugin docs for Zod validation

packages/plugin-errors/src/index.ts, packages/plugin-federation/src/index.ts, packages/plugin-relay/src/index.ts
From https://pothos-graphql.dev/docs/guide/writing-plugins#indexts:
> The plugins name, which should be typed as a string literal rather than as a generic string:
> const pluginName = 'example' as const;
=> Fix plugin names missing as const

packages/plugin-prisma/src/field-builder.ts, packages/plugin-prisma/src/index.ts, packages/plugin-prisma/src/prisma-field-builder.ts, packages/plugin-prisma/src/util/map-query.ts, packages/plugin-prisma/tests/counts.test.ts
Related to https://github.com/hayes/pothos/issues/989
=> Prevent executing connection resolver when only total count is selected

website/pages/docs/guide/args.mdx
The name should be `args` not `arg`.
=> docs(guide/args): fix args typo

.changeset/small-ads-cover.md, packages/plugin-prisma-utils/src/schema-builder.ts, packages/plugin-prisma-utils/tests/index.test.ts
`isNot` is used only for relation filter conditions.
=> feat: allow prismaFilters to filter for null values with not

.changeset/strong-ads-rescue.md, packages/core/tests/enums.test.ts
This pull request introduces tests designed to validate that enum types created using different structures are equivalent.
Each test scenario involves creating an enum type, integrating it into the query type of the schema, and then running two tests:
Introspection Test: Ensures that the schema correctly exposes enum values through GraphQL introspection.
Query Test: Validates the functionality of the enums for type and input.
=> test: add enum tests across enum creation options

packages/core/tests/enums.test.ts, website/pages/docs/guide/enums.mdx
Modern TypeScript may prefer using objects with as const over enums to align with JavaScript
standards. (or my personal preference `Object.freeze`).
Added a primary example using `Object.values` and a secondary example with `Object.keys`
with `enumType`
Added tests for both to prove documented method works
Closes #591
=> docs: add docs for using object as const for enumType

.changeset/sharp-phones-work.md, packages/plugin-prisma/src/generator.ts
Running `prisma generate` on windows won't generate the `esm/generated.ts` file, which results in the error
> Cannot find module '@pothos/plugin-prisma/generated' or its corresponding type declarations
when trying to import the pothos prisma types in an ESM project. The underlying problem is that the location replacements use unix-style path seperators (`/`), but `outputLocation` and `prismaLocation` use `\` on windows.
Instead of doing string replacements, I changed the code to use the `join` method from `node:path` which handles platform specific path delimiters.
Tested on windows with pnpm. Need to test wether generation still works on unix-like systems and with other package managers.
=> [plugin-prisma] Fix prisma generator not creating the ESM build on windows

.changeset/popular-cats-brush.md, packages/plugin-federation/README.md, packages/plugin-federation/src/external-ref.ts, packages/plugin-federation/src/global-types.ts, packages/plugin-federation/src/index.ts, packages/plugin-federation/src/schema-builder.ts, packages/plugin-federation/src/util.ts, packages/plugin-federation/tests/__snapshots__/compatability.test.ts.snap, packages/plugin-federation/tests/__snapshots__/index.test.ts.snap, packages/plugin-federation/tests/example/accounts/schema.ts, website/pages/docs/plugins/federation.mdx
See [issue 1125](https://github.com/hayes/pothos/issues/1125).
=> Allow override of federation directives

website/pages/docs/plugins/relay.mdx
Yeah, this is one of those PRs. but I couldn't just let `sucess` live on
=> fix(plugins/relay.mdx): typo

.changeset/tall-planes-relax.md, website/components/Layout.tsx
Collapsed details panel covered content due to full height. 
The change makes details panel to be full height only when is open and thus improves UX of copying code snippets that would have been covered by the details panel (see gif below).
=> Docs: Make details panel non-interactive when collapsed

packages/deno/packages/plugin-tracing/README.md, packages/plugin-tracing/README.md, packages/tracing-sentry/package.json, packages/tracing-sentry/tests/example/server.ts, pnpm-lock.yaml, website/pages/docs/plugins/tracing.mdx
I've updated Sentry examples to use v8 instead of v7 following [the migration guide](https://github.com/getsentry/sentry-javascript/blob/develop/MIGRATION.md#upgrading-from-7x-to-8x)
=> chore(tracing-sentry): Support Sentry v8

.changeset/lovely-needles-explode.md, eslint.config.js, packages/plugin-prisma/package.json, packages/plugin-prisma/src/types.ts, packages/plugin-prisma/tests/.gitignore, packages/plugin-prisma/tests/prisma-types-from-client/index.test-d.ts, packages/plugin-prisma/tests/prisma-types-from-client/schema.prisma, pnpm-lock.yaml, vitest.config.js
This PR makes `PrismaTypesFromClient` utility type able to infer [composite types](https://www.prisma.io/docs/orm/prisma-client/special-fields-and-types/composite-types) (which is only available with MongoDB)
=> Make `PrismaTypesFromClient` able to infer composite types

website/content/docs/guide/writing-plugins.mdx
First of all, I'd like to congrats on the release of v4!
While migrates some codes, I found `builer.configStore.onFieldUse` has been removed, and instead the `onFirstUse` method on `FieldRef` has been added. so I made a little change in Writing Plugins document.
=> docs: update documentation about onFirstUse method

.changeset/swift-yaks-shake.md, packages/tracing-sentry/package.json, pnpm-lock.yaml
The dependency on @sentry/tracing has been removed in this PR:
https://github.com/hayes/pothos/pull/1220/files#diff-ebc36762ab958f662687f4e52e77f8e99c4765d7bffea474d5936f2890f8e893L53
It seems it was mistakenly added during the v4 release:
https://github.com/hayes/pothos/pull/855/files#diff-ebc36762ab958f662687f4e52e77f8e99c4765d7bffea474d5936f2890f8e893R53
Since Sentry v8, @sentry/tracing has been removed, so it is correct to not have this dependency.
=> Remove @sentry/tracing from @pothos/sentry-tracing

.changeset/tricky-oranges-help.md, packages/plugin-relay/package.json, packages/plugin-relay/src/utils/connections.ts
This will be extremely helpful as I am writing relay connections for one of my projects and want to reuse this method to calculate relay cursor arguments from default connection args.
=> chore: export connection utilities + types

.changeset/nervous-shoes-grin.md, packages/plugin-scope-auth/src/request-cache.ts, packages/plugin-scope-auth/tests/__snapshots__/index.test.ts.snap, packages/plugin-scope-auth/tests/example/builder.ts, packages/plugin-scope-auth/tests/example/schema/index.ts, packages/plugin-scope-auth/tests/field-auth-scopes.test.ts
This PR binds scope loaders to the `scopes` object itself before execution. The motivation here is to allow passing in external classes that run authorization checks, such as the following pattern we tried when configuring `@pothos/plugin-scope-auth`:
```tsx
export const builder = new SchemaBuilder<{
Context: ResolverContext;
AuthScopes: {
canEditObject: string;
};
}>({
plugins: [ScopeAuthPlugin],
scopeAuth: { authScopes: (ctx) => ctx.auth },
});
```
where `ctx.auth` is an instance of a class that performs authorization checks e.g: 
```tsx
class AuthorizationChecker {
private readonly user: User;
canEditObject(objectUuid: string): Promise<boolean> {
// Performs some checks based on objectUuid and this.user.
}
}
```
Although this only saves us a few lines of code, it prevents issues where …
=> Bind auth scope loaders to scopes object

.changeset/strong-doors-swim.md, packages/plugin-drizzle/src/types.ts
Addresses https://github.com/hayes/pothos/issues/1370 by exporting the type in the `types` module
=> Export Object ref type in drizzle plugin

.changeset/selfish-ladybugs-study.md, packages/plugin-add-graphql/src/schema-builder.ts
this ensures native GraphQLInputObjectTypes with isOneOf enabled are correctly added to the pothos schema
=> fix(add-graphql): pass through isOneOf setting from input objects

.changeset/beige-socks-fetch.md, packages/plugin-drizzle/src/connection-helpers.ts, packages/plugin-drizzle/tests/__snapshots__/index.test.ts.snap, packages/plugin-drizzle/tests/connection-helpers.test.ts, packages/plugin-drizzle/tests/example/schema.graphql, packages/plugin-drizzle/tests/example/schema/user.ts
This PR enables using `drizzleConnectionHelper` to create advanced Drizzle connections outside Drizzle objects.
=> Allow entry connections with drizzleConnectionHelper
