packages/core/src/build-cache.ts, packages/core/src/plugins/merge-field-wrappers.ts, packages/core/src/plugins/resolve-wrapper.ts, packages/core/src/plugins/wrap-field.ts, packages/core/src/utils/index.ts, packages/plugin-auth/src/utils/resolve-permission-check.ts, packages/plugin-auth/src/utils/value-or-promise.ts
=> fix: use thenable instead of types.isPromise to support custom promise implementations

docs/plugins/smart-subscriptions.md
I updated the dependency for the plugin as it was the wrong one in the documentation.
=> Update Smart-Subscription Docs

docs/plugins/relay.md, package.json, packages/deno/packages/core/fieldUtils/input.ts, packages/deno/packages/core/index.ts, packages/deno/packages/core/types/index.ts, packages/deno/packages/core/utils/index.ts, packages/deno/packages/plugin-relay/README.md, packages/deno/packages/plugin-relay/global-types.ts, packages/deno/packages/plugin-relay/schema-builder.ts, packages/deno/packages/plugin-relay/types.ts, packages/deno/packages/plugin-relay/utils/connections.ts, packages/deno/packages/plugin-scope-auth/global-types.ts, packages/deno/packages/plugin-scope-auth/index.ts, packages/deno/packages/plugin-scope-auth/types.ts, packages/plugin-dataloader/CHANGELOG.md, packages/plugin-dataloader/package.json, packages/plugin-dataloader/tests/__snapshots__/index.test.ts.snap, packages/plugin-dataloader/tests/example/schema/index.ts, packages/plugin-dataloader/tests/index.test.ts, packages/plugin-relay/CHANGELOG.md, packages/plugin-relay/README.md, packages/plugin-relay/package.json, packages/plugin-relay/src/global-types.ts, packages/plugin-relay/src/schema-builder.ts, packages/plugin-relay/src/types.ts, packages/plugin-relay/src/utils/connections.ts, packages/plugin-relay/tests/__snapshots__/index.test.ts.snap, packages/plugin-relay/tests/examples/relay/schema/index.ts, packages/plugin-relay/tests/examples/relay/schema/numbers.ts, packages/plugin-relay/tests/index.test.ts
fixes #112 
fixes #110 
Successfully published:
- @giraphql/plugin-dataloader@2.6.0-alpha.0
- @giraphql/plugin-relay@2.10.0-alpha.0
=> relay improvements

docs/guide/inputs.md
Do we need to create a GiraffeInput from the exemple above or is it a doc mistake ?
=> Is the doc correct ?

.changeset/big-seals-promise.md, docs/plugins/prisma.md, packages/deno/packages/core/fieldUtils/input.ts, packages/deno/packages/plugin-relay/schema-builder.ts, packages/deno/packages/plugin-relay/utils/connections.ts, packages/plugin-prisma/README.md, packages/plugin-prisma/src/types.ts
=> feature(prisma): pass context to relation query options

.changeset/metal-flowers-kneel.md, packages/deno/packages/core/fieldUtils/input.ts, packages/deno/packages/plugin-relay/schema-builder.ts, packages/deno/packages/plugin-relay/utils/connections.ts, packages/plugin-prisma/src/field-builder.ts, packages/plugin-prisma/src/types.ts, packages/plugin-prisma/tests/__snapshots__/index.test.ts.snap, packages/plugin-prisma/tests/example/schema/index.ts
=> fix: don't distribute resolve type for nullable prismaField

.changeset/proud-donkeys-pretend.md, docs/guide/troubleshooting.md, docs/plugins/prisma.md, packages/plugin-prisma/README.md, packages/plugin-prisma/src/field-builder.ts, packages/plugin-prisma/src/global-types.ts, packages/plugin-prisma/src/model-loader.ts, packages/plugin-prisma/src/refs.ts, packages/plugin-prisma/src/schema-builder.ts, packages/plugin-prisma/src/types.ts, packages/plugin-prisma/tests/example/builder.ts, packages/plugin-prisma/tests/example/schema/index.ts
🦋  success packages published successfully:
🦋  @giraphql/converter@0.0.0-preview-202179204139
🦋  @giraphql/core@0.0.0-preview-202179204139
🦋  @giraphql/deno@0.0.0-preview-202179204139
🦋  @giraphql/plugin-dataloader@0.0.0-preview-202179204139
🦋  @giraphql/plugin-directives@0.0.0-preview-202179204139
🦋  @giraphql/plugin-errors@0.0.0-preview-202179204139
🦋  @giraphql/plugin-example@0.0.0-preview-202179204139
🦋  @giraphql/plugin-mocks@0.0.0-preview-202179204139
🦋  @giraphql/plugin-prisma@0.0.0-preview-202179204139
🦋  @giraphql/plugin-relay@0.0.0-preview-202179204139
🦋  @giraphql/plugin-scope-auth@0.0.0-preview-202179204139
🦋  @giraphql/plugin-simple-objects@0.0.0-preview-202179204139
🦋  @giraphql/plugin-smart-subscriptions@0.0.0-preview-202179204139
🦋 …
=> rework prisma plugin types to improve type-checking performance

docs/plugins/errors.md
Fixes a small typo in the docs.
=> Fix typo in errors.md

packages/plugin-validation/README.md
Remove beta-notice for zod@3 and make it the default as it is stable for quite a while now.
=> Remove beta-notice for zod

docs/guide/fields.md, docs/guide/interfaces.md, docs/guide/objects.md, packages/core/tests/examples/giraffes/inputs.ts, packages/core/tests/examples/giraffes/interfaces.ts, packages/core/tests/examples/giraffes/objects.ts, packages/core/tests/examples/giraffes/scalars.ts
This avoids some silly timezone shenanigans
=> tests: creates dates in UTC

docs/plugins/prisma.md
(PS: Transition works smooth so far. Great job!)
=> Remove doubled leftover-import of "PrismaTypes"

.changeset/young-lizards-fry.md, docs/plugins/dataloader.md, docs/plugins/prisma.md, packages/plugin-dataloader/README.md, packages/plugin-dataloader/src/field-builder.ts, packages/plugin-dataloader/src/index.ts, packages/plugin-dataloader/src/schema-builder.ts, packages/plugin-dataloader/src/types.ts, packages/plugin-dataloader/src/util.ts, packages/plugin-dataloader/tests/__snapshots__/index.test.ts.snap, packages/plugin-dataloader/tests/example/schema/counts.ts, packages/plugin-dataloader/tests/example/schema/fields.ts, packages/plugin-dataloader/tests/example/schema/objects.ts, packages/plugin-dataloader/tests/index.test.ts, packages/plugin-prisma/README.md
Preview version:
```
@giraphql/plugin-dataloader@0.0.0-preview-20218132243
```
=> Add new sort and toKey options to dataloader plugin

docs/plugins/scope-auth.md
I'm actually not sure about this change but I don't know how best to ask docs questions.
=> coolPerm missing

.changeset/wicked-cycles-destroy.md, docs/plugins/prisma.md, packages/plugin-prisma/README.md, packages/plugin-prisma/generated.ts, packages/plugin-prisma/src/prisma-field-builder.ts, packages/plugin-prisma/src/util/map-includes.ts, packages/plugin-prisma/tests/__snapshots__/index.test.ts.snap, packages/plugin-prisma/tests/example/schema/index.ts, packages/plugin-prisma/tests/relation-query.test.ts
fixes: #199, #200 
Snapshot release:
```
@giraphql/plugin-prisma@0.0.0-preview-202192619401
```
=> Pass context to query and add generated.ts to exports

.changeset/little-dolphins-care.md, packages/core/src/refs/input-object.ts, packages/core/src/types/utils.ts, packages/core/tests/__snapshots__/index.test.ts.snap, packages/core/tests/examples/random-stuff.ts
Some tests are failing, needs further investigation.
Not 100% sure this is actually something that should be fixed/supported.
=> Fix issue related to inputRef defined with a union being unimplementable

.changeset/curvy-zebras-tie.md, .config/beemo/eslint.ts, packages/deno/packages/plugin-scope-auth/errors.ts, packages/deno/packages/plugin-scope-auth/global-types.ts, packages/deno/packages/plugin-scope-auth/index.ts, packages/deno/packages/plugin-scope-auth/request-cache.ts, packages/deno/packages/plugin-scope-auth/resolve-helper.ts, packages/deno/packages/plugin-scope-auth/resolve-state.ts, packages/deno/packages/plugin-scope-auth/steps.ts, packages/deno/packages/plugin-scope-auth/types.ts, packages/plugin-prisma/src/types.ts, packages/plugin-scope-auth/src/errors.ts, packages/plugin-scope-auth/src/global-types.ts, packages/plugin-scope-auth/src/index.ts, packages/plugin-scope-auth/src/request-cache.ts, packages/plugin-scope-auth/src/resolve-helper.ts, packages/plugin-scope-auth/src/resolve-state.ts, packages/plugin-scope-auth/src/steps.ts, packages/plugin-scope-auth/src/types.ts, packages/plugin-scope-auth/tests/__snapshots__/index.test.ts.snap, packages/plugin-scope-auth/tests/custom-error-message.test.ts, packages/plugin-scope-auth/tests/example/schema/custom-errors.ts, packages/plugin-scope-auth/tests/example/schema/index.ts, website/pages/docs/plugins/scope-auth.mdx
=> Custom auth errors

website/pages/docs/plugins/federation.mdx
I can't figure out where `ReviewType` might come from so haven't attempted to fix
=> Undeclared stuff in federation docs

.changeset/chilled-timers-smile.md, packages/core/src/types/global/schema-types.ts, packages/core/src/types/schema-types.ts, packages/core/src/types/utils.ts, packages/plugin-directives/src/global-types.ts, packages/plugin-prisma/src/global-types.ts, packages/plugin-relay/src/global-types.ts, packages/plugin-scope-auth/src/global-types.ts, packages/plugin-sub-graph/src/global-types.ts, packages/plugin-with-input/src/global-types.ts, website/pages/docs/guide/writing-plugins.mdx
fixes #319 
New experience when strict mode is disabled:
https://user-images.githubusercontent.com/816527/163256976-5af250c8-ce38-4af9-81ec-d7db590c99ef.mov
Several plugins have been updated to work better with strict mode disabled, but user should still have it enabled if possible.
=> Improve non-strict user experience

README.md, website/pages/docs/sponsors.mdx
Thank you for the sponsorship @KATT!
Do you have a preference for how you are listed, or where I should link to in the sponsors list?
`tRPC` looks really cool btw.  I am a huge fan of libraries like yours that take typescript developer experience to the next level.
=> Add sponsorship from @KATT

README.md, website/pages/docs/sponsors.mdx
Thanks for the sponsorship @robmcguinness! I really appreciate it.  Adding you to the sponsors list in the PR, If you have any preferences on what I should link to, or how you appear on the list (name, github handle, logo, etc) Just let me know.
=> Add @robmcguinness to sponsors list

examples/simple-classes/src/schema.ts, examples/simple-interfaces/src/schema.ts
This example was very helpful to me, thank you.
I noticed some small inconsistencies.
=> Small fixes in examples / simple-interfaces

README.md, website/pages/docs/sponsors.mdx
Thanks so much @Gomah for the sponsorship!
Sorry it took me a few days to get around to this, I've been camping the last few days and haven't had service.
If you have any preference on how you are listed in the sponsors list, just let me know here, and I can update the link/name
=> Add Gomah to sponsors list

.changeset/good-seals-tap.md, examples/prisma-federation/src/db.ts, examples/prisma-relay/src/db.ts, examples/prisma/src/db.ts, packages/plugin-prisma/src/util/get-client.ts, packages/plugin-prisma/tests/example/builder.ts
resolves #423 
Will need to wait for https://github.com/prisma/prisma/pull/13811 to test that this actually works correctly.
=> Support prisma@4

README.md
Consider this my alternative to financial contribution.
=> Remove duplicated sponsors section

packages/plugin-prisma/README.md, website/pages/docs/plugins/prisma.mdx
You have a really amazing project here! It's been a joy playing around with it these past couple of evenings. I hope to contribute more than just a typo change as I dig deeper!
Thanks!
=> docs(prisma): fix spelling of queries

website/pages/docs/plugins/smart-subscriptions.mdx
There should be no paragraphs here:
=> docs: Fix bad formatting of smart-subscriptions.md

website/pages/docs/guide/app-layout.mdx
Something went wrong with this formatting, again. But I'll fix these issues when I find them again 😄
=> docs: fix Fix bad formatting of app-layout.mdx

website/pages/docs/guide/troubleshooting.mdx
=> docs: troubleshooting guide for multiple plugin implementations

packages/plugin-errors/README.md, packages/plugin-scope-auth/README.md, packages/plugin-sub-graph/README.md, packages/plugin-validation/README.md, website/pages/docs/api/input-field-builder.mdx, website/pages/docs/api/schema-builder.mdx, website/pages/docs/guide/changing-default-nullability.mdx, website/pages/docs/guide/troubleshooting.mdx, website/pages/docs/guide/writing-plugins.mdx, website/pages/docs/plugins/errors.mdx, website/pages/docs/plugins/scope-auth.mdx, website/pages/docs/plugins/sub-graph.mdx, website/pages/docs/plugins/validation.mdx
This PR fixes a bunch of formatting issues on the docs site, mostly unnecessary new lines.
=> Fix various docs formatting issues

README.md, website/pages/docs/sponsors.mdx
Thanks so much for the sponsorship @evilkiwi / @OYED
=> Add @evilkiwi to sponsors

.changeset/nine-readers-rush.md, packages/plugin-prisma/prisma/schema.prisma, packages/plugin-prisma/src/generator.ts
=> Fix orerBy when fullTextSearch is enabled

website/pages/docs/guide/circular-references.mdx, website/pages/docs/guide/scalars.mdx, website/pages/docs/guide/using-plugins.mdx
Thanks for a great library, @hayes! I found some mistakes in the documents, so fixed them.
=> Few cosmetic fixes to the documents

.changeset/swift-cooks-drive.md, examples/complex-app/package.json, examples/prisma-federation/package.json, examples/prisma-relay/package.json, examples/prisma/package.json, examples/relay-windowed-pagination/package.json, packages/plugin-prisma-utils/package.json, packages/plugin-prisma/README.md, packages/plugin-prisma/package.json, packages/plugin-prisma/prisma/schema.prisma, packages/plugin-prisma/prisma/seed.mjs, packages/plugin-prisma/src/global-types.ts, packages/plugin-prisma/src/model-loader.ts, packages/plugin-prisma/src/prisma-field-builder.ts, packages/plugin-prisma/src/types.ts, packages/plugin-prisma/src/util/map-query.ts, packages/plugin-prisma/src/util/selections.ts, packages/plugin-prisma/tests/__snapshots__/index.test.ts.snap, packages/plugin-prisma/tests/counts.test.ts, packages/plugin-prisma/tests/example/builder.ts, packages/plugin-prisma/tests/example/schema/index.ts, packages/plugin-prisma/tests/nested-query.test.ts, packages/plugin-scope-auth/package.json, pnpm-lock.yaml, website/pages/docs/plugins/prisma.mdx
=> Support prisma filtered relation counts

.changeset/chilly-kangaroos-type.md, README.md, scripts/esm-transformer.ts, website/pages/docs/sponsors.mdx
Thanks for the sponsorship @garth!
=> Add @garth to sponsors

.changeset/khaki-points-sing.md, README.md, packages/plugin-prisma/src/field-builder.ts, packages/plugin-prisma/src/types.ts, website/pages/docs/sponsors.mdx
thanks for the sponsorships @lifedup and @jacobgmathew
=> nullable prisma connection

website/pages/docs/guide/schema-builder.mdx
Make minor typo fixes to schema-builder.mdx
Fix minor typos, nothing subjective or that could change meaning.
=> Make minor typo fixes to schema-builder.mdx

.changeset/fair-wombats-try.md, packages/deno/packages/plugin-relay/utils/connections.ts, packages/plugin-relay/src/utils/connections.ts
=> Make `resolveArrayConnection` return type non-nullable

website/pages/docs/guide/app-layout.mdx, website/pages/docs/guide/changing-default-nullability.mdx, website/pages/docs/guide/enums.mdx
Fix minor typos, ignoring anything that could change meaning.
=> Make minor website copy updates and fixes

.changeset/soft-sloths-report.md, packages/deno/packages/core/config-store.ts, packages/deno/packages/migration/mod.ts, packages/deno/packages/plugin-add-graphql/mod.ts, packages/deno/packages/plugin-mocks/README.md, packages/deno/packages/plugin-relay/README.md, packages/deno/packages/plugin-relay/global-types.ts, packages/deno/packages/plugin-relay/schema-builder.ts, packages/deno/packages/plugin-sub-graph/README.md, packages/plugin-relay/README.md, packages/plugin-relay/src/global-types.ts, packages/plugin-relay/src/schema-builder.ts, packages/plugin-relay/tests/__snapshots__/index.test.ts.snap, packages/plugin-relay/tests/examples/relay/schema/poll.ts, website/pages/docs/plugins/relay.mdx
Related to https://github.com/hayes/pothos/discussions/774
=> Add nodeField to relay edgeObject and edgesField to relay connectionObject

packages/plugin-prisma/generated.ts
Spotted broken link and updated it!
=> Fixed broken link

website/pages/docs/guide/fields.mdx
I noticed two minor typos while reading the guide on fields.
=> Fix minor typos

packages/deno/packages/migration/mod.ts, packages/deno/packages/plugin-add-graphql/mod.ts, packages/deno/packages/plugin-scope-auth/README.md, packages/plugin-scope-auth/README.md, website/pages/docs/plugins/scope-auth.mdx
Fixes #708
Ran into this myself and took a crack at clarifying in the docs a bit.
=> docs: add context to scope-auth plugin ordering relative to relay

.changeset/heavy-schools-relate.md, .changeset/ten-spoons-sort.md, examples/prisma-federation/package.json, examples/prisma-smart-subscriptions-apollo/package.json, packages/deno/packages/plugin-directives/README.md, packages/deno/packages/plugin-directives/global-types.ts, packages/deno/packages/plugin-directives/index.ts, packages/plugin-directives/README.md, packages/plugin-directives/src/global-types.ts, packages/plugin-directives/src/index.ts, packages/plugin-federation/README.md, packages/plugin-federation/package.json, packages/plugin-federation/src/global-types.ts, packages/plugin-federation/src/index.ts, packages/plugin-federation/src/schema-builder.ts, packages/plugin-federation/tests/__snapshots__/index.test.ts.snap, packages/plugin-federation/tests/example/accounts/schema.ts, packages/plugin-federation/tests/example/products/schema.ts, packages/plugin-federation/tests/index.test.ts, pnpm-lock.yaml, website/pages/docs/plugins/directives.mdx, website/pages/docs/plugins/federation.mdx
=> Add support for new federation directives

packages/plugin-relay/README.md, website/pages/docs/plugins/relay.mdx
=> Fix minor typo in relay plugin docs

website/pages/docs/guide/using-plugins.mdx
=> fix: single typo in docs using-plugins.mdx

website/pages/docs/plugins/smart-subscriptions.mdx
=> Update smart-subscriptions.mdx (minor typo)

website/pages/docs/plugins/simple-objects.mdx
Update formatting for Simple Objects plugin documentation to match plugin expectations
=> Update Simple Objects plugin documentation

.changeset/olive-dancers-fix.md, packages/core/src/utils/base64.ts
fixes: https://github.com/hayes/pothos/issues/1023
=> fix: prefer global Buffer for b64 conversion

website/pages/docs/plugins/errors.mdx
Reference correct plugin names
=> Update error plugin documentation to reference correct plugin names

.changeset/stale-bats-train.md, packages/plugin-federation/src/global-types.ts, packages/plugin-federation/src/index.ts, packages/plugin-federation/src/schema-builder.ts, packages/plugin-federation/tests/__snapshots__/compatability.test.ts.snap, packages/plugin-federation/tests/__snapshots__/index.test.ts.snap, packages/plugin-federation/tests/example/accounts/schema.ts, website/pages/docs/plugins/federation.mdx
[Link to issue](https://github.com/hayes/pothos/issues/1114)
=> Issue 1114 - Update apollo federation version

.changeset/happy-cars-hunt.md, packages/plugin-smart-subscriptions/src/index.ts
as per [intended design](https://github.com/hayes/pothos/issues/1141).
=> if debounceDelay is null, keep it null

.changeset/small-ravens-guess.md, packages/plugin-federation/src/global-types.ts
hey, we use your lib and need support for the progressive override feature as seen here 
https://www.apollographql.com/docs/federation/entities-advanced/#incremental-migration-with-override
Thanks :)
=> add support for progressive override in federation

website/content/docs/plugins/relay.mdx
=> docs: mention relay plugin's builder.nodeInterfaceRef

.changeset/cold-cups-love.md, packages/plugin-prisma/src/schema-builder.ts
This PR is a fix that corresponds to the change of relay option in v4
=> Fix ref relay options in plugin-prisma

.changeset/nice-fishes-switch.md, packages/plugin-drizzle/src/model-loader.ts, packages/plugin-prisma/src/model-loader.ts
Resolves https://github.com/hayes/pothos/issues/1327
=> Keep Prisma delegate in-sync with client cache

.github/workflows/pkg-pr-new.yml, package.json, patches/@changesets__assemble-release-plan.patch, pnpm-lock.yaml
This PR configures continuous releases using [pkg.pr.new](https://github.com/stackblitz-labs/pkg.pr.new).
To function properly, [the GitHub application](https://github.com/apps/pkg-pr-new) should be installed on the repo.
=> Setup pkg.pr.new

website/content/docs/resources.mdx
As per https://github.com/hayes/pothos/discussions/1414#discussioncomment-12784231
=> Add rumble to 3rd party tools

.changeset/good-mice-worry.md, packages/converter/src/index.ts, packages/core/src/build-cache.ts, packages/core/src/builder.ts, packages/core/src/types/type-params.ts, packages/core/tests/custom-roots.test.ts, packages/core/tests/examples/custom-root-names.ts
=> [core] support 'Subscription' as non-root type

.changeset/dull-chairs-shout.md, packages/plugin-errors/src/index.ts, packages/plugin-errors/tests/__snapshots__/index.test.ts.snap, packages/plugin-errors/tests/example/schema.ts, packages/plugin-errors/tests/index.test.ts
=> [errors] handle errors in subscriptions

.changeset/modern-facts-trade.md, packages/plugin-federation/src/global-types.ts, packages/plugin-federation/src/index.ts, packages/plugin-federation/tests/__snapshots__/index.test.ts.snap, packages/plugin-federation/tests/example/accounts/schema.ts
Add support to the cost and listsize directive
reference
https://www.apollographql.com/docs/graphos/schema-design/federated-schemas/reference/directives#cost
=> add cost and list size directives

.changeset/all-yaks-live.md, packages/plugin-drizzle/package.json, packages/plugin-drizzle/src/connection-helpers.ts, packages/plugin-drizzle/src/drizzle-field-builder.ts, packages/plugin-drizzle/src/global-types.ts, packages/plugin-drizzle/src/interface-ref.ts, packages/plugin-drizzle/src/model-loader.ts, packages/plugin-drizzle/src/node-ref.ts, packages/plugin-drizzle/src/object-ref.ts, packages/plugin-drizzle/src/schema-builder.ts, packages/plugin-drizzle/src/types.ts, packages/plugin-drizzle/src/utils/config.ts, packages/plugin-drizzle/src/utils/cursors.ts, packages/plugin-drizzle/src/utils/selections.ts, packages/plugin-drizzle/tests/example/schema/user.ts, pnpm-lock.yaml
=> [drizzle] Update drizzle plugin to work with latest beta release

website/content/docs/resources.mdx
I was going to add it to the bottom of the list of templates, but the others all seem unmaintained/outdated. Let me know what you think.
=> Add Nakazawa Tech's server template + Talk
